name: Check formatting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Check PEP8 compliance with flake8
        run: |
          pip install flake8
          flake8 mcx tests --count --ignore=E501,E203,E731,W503 --show-source --statistics

      - name: Check formatting with black
        run: |
          pip install black
          black --check mcx tests

      - name: Check types with mypy
        run: |
          pip install mypy
          mypy mcx tests
